/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;
using System.Reflection;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// CommonOperationResponseTransactionsInnerData
    /// </summary>
    [JsonConverter(typeof(CommonOperationResponseTransactionsInnerDataJsonConverter))]
    [DataContract(Name = "CommonOperationResponse_transactions_inner_data")]
    public partial class CommonOperationResponseTransactionsInnerData : AbstractOpenAPISchema
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationResponseTransactionsInnerData" /> class.
        /// </summary>
        public CommonOperationResponseTransactionsInnerData()
        {
            this.IsNullable = true;
            this.SchemaType= "oneOf";
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationResponseTransactionsInnerData" /> class
        /// with the <see cref="string" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of string.</param>
        public CommonOperationResponseTransactionsInnerData(string actualInstance)
        {
            this.IsNullable = true;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationResponseTransactionsInnerData" /> class
        /// with the <see cref="decimal" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of decimal.</param>
        public CommonOperationResponseTransactionsInnerData(decimal actualInstance)
        {
            this.IsNullable = true;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationResponseTransactionsInnerData" /> class
        /// with the <see cref="bool" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of bool.</param>
        public CommonOperationResponseTransactionsInnerData(bool actualInstance)
        {
            this.IsNullable = true;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationResponseTransactionsInnerData" /> class
        /// with the <see cref="Dictionary{string, Object}" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of Dictionary&lt;string, Object&gt;.</param>
        public CommonOperationResponseTransactionsInnerData(Dictionary<string, Object> actualInstance)
        {
            this.IsNullable = true;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonOperationResponseTransactionsInnerData" /> class
        /// with the <see cref="List{Object}" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of List&lt;Object&gt;.</param>
        public CommonOperationResponseTransactionsInnerData(List<Object> actualInstance)
        {
            this.IsNullable = true;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance;
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(Dictionary<string, Object>))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(List<Object>))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(bool))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(decimal))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(string))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: Dictionary<string, Object>, List<Object>, bool, decimal, string");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `string`. If the actual instance is not `string`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of string</returns>
        public string GetString()
        {
            return (string)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `decimal`. If the actual instance is not `decimal`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of decimal</returns>
        public decimal GetDecimal()
        {
            return (decimal)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `bool`. If the actual instance is not `bool`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of bool</returns>
        public bool GetBool()
        {
            return (bool)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `Dictionary&lt;string, Object&gt;`. If the actual instance is not `Dictionary&lt;string, Object&gt;`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of Dictionary&lt;string, Object&gt;</returns>
        public Dictionary<string, Object> GetDictionary()
        {
            return (Dictionary<string, Object>)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `List&lt;Object&gt;`. If the actual instance is not `List&lt;Object&gt;`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of List&lt;Object&gt;</returns>
        public List<Object> GetList()
        {
            return (List<Object>)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CommonOperationResponseTransactionsInnerData {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, CommonOperationResponseTransactionsInnerData.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of CommonOperationResponseTransactionsInnerData
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of CommonOperationResponseTransactionsInnerData</returns>
        public static CommonOperationResponseTransactionsInnerData FromJson(string jsonString)
        {
            CommonOperationResponseTransactionsInnerData newCommonOperationResponseTransactionsInnerData = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newCommonOperationResponseTransactionsInnerData;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(Dictionary<string, Object>).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationResponseTransactionsInnerData = new CommonOperationResponseTransactionsInnerData(JsonConvert.DeserializeObject<Dictionary<string, Object>>(jsonString, CommonOperationResponseTransactionsInnerData.SerializerSettings));
                }
                else
                {
                    newCommonOperationResponseTransactionsInnerData = new CommonOperationResponseTransactionsInnerData(JsonConvert.DeserializeObject<Dictionary<string, Object>>(jsonString, CommonOperationResponseTransactionsInnerData.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("Dictionary<string, Object>");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into Dictionary<string, Object>: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(List<Object>).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationResponseTransactionsInnerData = new CommonOperationResponseTransactionsInnerData(JsonConvert.DeserializeObject<List<Object>>(jsonString, CommonOperationResponseTransactionsInnerData.SerializerSettings));
                }
                else
                {
                    newCommonOperationResponseTransactionsInnerData = new CommonOperationResponseTransactionsInnerData(JsonConvert.DeserializeObject<List<Object>>(jsonString, CommonOperationResponseTransactionsInnerData.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("List<Object>");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into List<Object>: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(bool).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationResponseTransactionsInnerData = new CommonOperationResponseTransactionsInnerData(JsonConvert.DeserializeObject<bool>(jsonString, CommonOperationResponseTransactionsInnerData.SerializerSettings));
                }
                else
                {
                    newCommonOperationResponseTransactionsInnerData = new CommonOperationResponseTransactionsInnerData(JsonConvert.DeserializeObject<bool>(jsonString, CommonOperationResponseTransactionsInnerData.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("bool");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into bool: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(decimal).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationResponseTransactionsInnerData = new CommonOperationResponseTransactionsInnerData(JsonConvert.DeserializeObject<decimal>(jsonString, CommonOperationResponseTransactionsInnerData.SerializerSettings));
                }
                else
                {
                    newCommonOperationResponseTransactionsInnerData = new CommonOperationResponseTransactionsInnerData(JsonConvert.DeserializeObject<decimal>(jsonString, CommonOperationResponseTransactionsInnerData.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("decimal");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into decimal: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(string).GetProperty("AdditionalProperties") == null)
                {
                    newCommonOperationResponseTransactionsInnerData = new CommonOperationResponseTransactionsInnerData(JsonConvert.DeserializeObject<string>(jsonString, CommonOperationResponseTransactionsInnerData.SerializerSettings));
                }
                else
                {
                    newCommonOperationResponseTransactionsInnerData = new CommonOperationResponseTransactionsInnerData(JsonConvert.DeserializeObject<string>(jsonString, CommonOperationResponseTransactionsInnerData.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("string");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into string: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newCommonOperationResponseTransactionsInnerData;
        }

    }

    /// <summary>
    /// Custom JSON converter for CommonOperationResponseTransactionsInnerData
    /// </summary>
    public class CommonOperationResponseTransactionsInnerDataJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(CommonOperationResponseTransactionsInnerData).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return CommonOperationResponseTransactionsInnerData.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
