/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// CommonAssetActivityRequestInput
    /// </summary>
    [DataContract(Name = "CommonAssetActivityRequestInput")]
    [UnityEngine.Scripting.Preserve]
    public partial class CommonAssetActivityRequestInput
    {
        /// <summary>
        /// Defines Types
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum TypesEnum
        {
            /// <summary>
            /// Enum Ask for value: ask
            /// </summary>
            [EnumMember(Value = "ask")]
            Ask = 1,

            /// <summary>
            /// Enum AskCancel for value: ask_cancel
            /// </summary>
            [EnumMember(Value = "ask_cancel")]
            AskCancel = 2,

            /// <summary>
            /// Enum Bid for value: bid
            /// </summary>
            [EnumMember(Value = "bid")]
            Bid = 3,

            /// <summary>
            /// Enum BidCancel for value: bid_cancel
            /// </summary>
            [EnumMember(Value = "bid_cancel")]
            BidCancel = 4,

            /// <summary>
            /// Enum Sale for value: sale
            /// </summary>
            [EnumMember(Value = "sale")]
            Sale = 5,

            /// <summary>
            /// Enum Mint for value: mint
            /// </summary>
            [EnumMember(Value = "mint")]
            Mint = 6,

            /// <summary>
            /// Enum Transfer for value: transfer
            /// </summary>
            [EnumMember(Value = "transfer")]
            Transfer = 7
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CommonAssetActivityRequestInput" /> class.
        /// </summary>
        /// <param name="limit">limit (default to 20M).</param>
        /// <param name="types">types.</param>
        /// <param name="chainId">chainId (default to 13337).</param>
        /// <param name="continuation">continuation.</param>
        [UnityEngine.Scripting.Preserve]
        public CommonAssetActivityRequestInput(decimal limit = 20M, List<TypesEnum> types = default(List<TypesEnum>), long chainId = 13337, string continuation = default(string))
        {
            this.Limit = limit;
            this.Types = types;
            this.ChainId = chainId;
            this.Continuation = continuation;
        }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        [UnityEngine.Scripting.Preserve]
        public decimal Limit { get; set; }

        /// <summary>
        /// Gets or Sets Types
        /// </summary>
        [DataMember(Name = "types", EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public List<CommonAssetActivityRequestInput.TypesEnum> Types { get; set; }

        /// <summary>
        /// Gets or Sets ChainId
        /// </summary>
        [DataMember(Name = "chainId", EmitDefaultValue = false)]
        [UnityEngine.Scripting.Preserve]
        public long ChainId { get; set; }

        /// <summary>
        /// Gets or Sets Continuation
        /// </summary>
        [DataMember(Name = "continuation", EmitDefaultValue = true)]
        [UnityEngine.Scripting.Preserve]
        public string Continuation { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CommonAssetActivityRequestInput {\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("  Types: ").Append(Types).Append("\n");
            sb.Append("  ChainId: ").Append(ChainId).Append("\n");
            sb.Append("  Continuation: ").Append(Continuation).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        [UnityEngine.Scripting.Preserve]
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
