/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// GetAssetsForContractBodyInput
    /// </summary>
    [DataContract(Name = "GetAssetsForContractBodyInput")]
    public partial class GetAssetsForContractBodyInput
    {
        /// <summary>
        /// Defines SortDirection
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SortDirectionEnum
        {
            /// <summary>
            /// Enum Asc for value: asc
            /// </summary>
            [EnumMember(Value = "asc")]
            Asc = 1,

            /// <summary>
            /// Enum Desc for value: desc
            /// </summary>
            [EnumMember(Value = "desc")]
            Desc = 2
        }


        /// <summary>
        /// Gets or Sets SortDirection
        /// </summary>
        [DataMember(Name = "sortDirection", EmitDefaultValue = false)]
        public SortDirectionEnum? SortDirection { get; set; }
        /// <summary>
        /// Defines SortBy
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum SortByEnum
        {
            /// <summary>
            /// Enum FloorAskPrice for value: floorAskPrice
            /// </summary>
            [EnumMember(Value = "floorAskPrice")]
            FloorAskPrice = 1,

            /// <summary>
            /// Enum TokenId for value: tokenId
            /// </summary>
            [EnumMember(Value = "tokenId")]
            TokenId = 2,

            /// <summary>
            /// Enum Rarity for value: rarity
            /// </summary>
            [EnumMember(Value = "rarity")]
            Rarity = 3,

            /// <summary>
            /// Enum UpdatedAt for value: updatedAt
            /// </summary>
            [EnumMember(Value = "updatedAt")]
            UpdatedAt = 4
        }


        /// <summary>
        /// Gets or Sets SortBy
        /// </summary>
        [DataMember(Name = "sortBy", EmitDefaultValue = false)]
        public SortByEnum? SortBy { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetAssetsForContractBodyInput" /> class.
        /// </summary>
        /// <param name="continuation">continuation.</param>
        /// <param name="chainId">chainId (default to 13337M).</param>
        /// <param name="minRarityRank">minRarityRank.</param>
        /// <param name="maxRarityRank">maxRarityRank.</param>
        /// <param name="minFloorAskPrice">minFloorAskPrice.</param>
        /// <param name="maxFloorAskPrice">maxFloorAskPrice.</param>
        /// <param name="includeAttributes">includeAttributes (default to false).</param>
        /// <param name="attributes">attributes.</param>
        /// <param name="sortDirection">sortDirection (default to SortDirectionEnum.Asc).</param>
        /// <param name="sortBy">sortBy (default to SortByEnum.FloorAskPrice).</param>
        /// <param name="limit">limit (default to 20M).</param>
        public GetAssetsForContractBodyInput(string continuation = default(string), decimal chainId = 13337M, int? minRarityRank = default(int?), int? maxRarityRank = default(int?), decimal? minFloorAskPrice = default(decimal?), decimal? maxFloorAskPrice = default(decimal?), bool? includeAttributes = false, List<GetAssetsForContractBodyInputAttributesInner> attributes = default(List<GetAssetsForContractBodyInputAttributesInner>), SortDirectionEnum? sortDirection = SortDirectionEnum.Asc, SortByEnum? sortBy = SortByEnum.FloorAskPrice, decimal limit = 20M)
        {
            this.Continuation = continuation;
            this.ChainId = chainId;
            this.MinRarityRank = minRarityRank;
            this.MaxRarityRank = maxRarityRank;
            this.MinFloorAskPrice = minFloorAskPrice;
            this.MaxFloorAskPrice = maxFloorAskPrice;
            // use default value if no "includeAttributes" provided
            this.IncludeAttributes = includeAttributes ?? false;
            this.Attributes = attributes;
            this.SortDirection = sortDirection;
            this.SortBy = sortBy;
            this.Limit = limit;
        }

        /// <summary>
        /// Gets or Sets Continuation
        /// </summary>
        [DataMember(Name = "continuation", EmitDefaultValue = true)]
        public string Continuation { get; set; }

        /// <summary>
        /// Gets or Sets ChainId
        /// </summary>
        [DataMember(Name = "chainId", EmitDefaultValue = false)]
        public decimal ChainId { get; set; }

        /// <summary>
        /// Gets or Sets MinRarityRank
        /// </summary>
        [DataMember(Name = "minRarityRank", EmitDefaultValue = true)]
        public int? MinRarityRank { get; set; }

        /// <summary>
        /// Gets or Sets MaxRarityRank
        /// </summary>
        [DataMember(Name = "maxRarityRank", EmitDefaultValue = true)]
        public int? MaxRarityRank { get; set; }

        /// <summary>
        /// Gets or Sets MinFloorAskPrice
        /// </summary>
        [DataMember(Name = "minFloorAskPrice", EmitDefaultValue = true)]
        public decimal? MinFloorAskPrice { get; set; }

        /// <summary>
        /// Gets or Sets MaxFloorAskPrice
        /// </summary>
        [DataMember(Name = "maxFloorAskPrice", EmitDefaultValue = true)]
        public decimal? MaxFloorAskPrice { get; set; }

        /// <summary>
        /// Gets or Sets IncludeAttributes
        /// </summary>
        [DataMember(Name = "includeAttributes", EmitDefaultValue = true)]
        public bool? IncludeAttributes { get; set; }

        /// <summary>
        /// Gets or Sets Attributes
        /// </summary>
        [DataMember(Name = "attributes", EmitDefaultValue = true)]
        public List<GetAssetsForContractBodyInputAttributesInner> Attributes { get; set; }

        /// <summary>
        /// Gets or Sets Limit
        /// </summary>
        [DataMember(Name = "limit", EmitDefaultValue = false)]
        public decimal Limit { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetAssetsForContractBodyInput {\n");
            sb.Append("  Continuation: ").Append(Continuation).Append("\n");
            sb.Append("  ChainId: ").Append(ChainId).Append("\n");
            sb.Append("  MinRarityRank: ").Append(MinRarityRank).Append("\n");
            sb.Append("  MaxRarityRank: ").Append(MaxRarityRank).Append("\n");
            sb.Append("  MinFloorAskPrice: ").Append(MinFloorAskPrice).Append("\n");
            sb.Append("  MaxFloorAskPrice: ").Append(MaxFloorAskPrice).Append("\n");
            sb.Append("  IncludeAttributes: ").Append(IncludeAttributes).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  SortDirection: ").Append(SortDirection).Append("\n");
            sb.Append("  SortBy: ").Append(SortBy).Append("\n");
            sb.Append("  Limit: ").Append(Limit).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
