/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// GetTransactionResponseUserEntitiesInner
    /// </summary>
    [DataContract(Name = "GetTransactionResponse_user_entities_inner")]
    public partial class GetTransactionResponseUserEntitiesInner
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetTransactionResponseUserEntitiesInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetTransactionResponseUserEntitiesInner() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetTransactionResponseUserEntitiesInner" /> class.
        /// </summary>
        /// <param name="entityId">entityId (required).</param>
        public GetTransactionResponseUserEntitiesInner(string entityId = default(string))
        {
            // to ensure "entityId" is required (not null)
            if (entityId == null)
            {
                throw new ArgumentNullException("entityId is a required property for GetTransactionResponseUserEntitiesInner and cannot be null");
            }
            this.EntityId = entityId;
        }

        /// <summary>
        /// Gets or Sets EntityId
        /// </summary>
        [DataMember(Name = "entityId", IsRequired = true, EmitDefaultValue = true)]
        public string EntityId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetTransactionResponseUserEntitiesInner {\n");
            sb.Append("  EntityId: ").Append(EntityId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
