/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// GetUserNativeCurrencyResponse
    /// </summary>
    [DataContract(Name = "GetUserNativeCurrencyResponse")]
    public partial class GetUserNativeCurrencyResponse
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUserNativeCurrencyResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected GetUserNativeCurrencyResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="GetUserNativeCurrencyResponse" /> class.
        /// </summary>
        /// <param name="nativeTokenBalance">nativeTokenBalance (required).</param>
        public GetUserNativeCurrencyResponse(GetUserNativeCurrencyResponseNativeTokenBalance nativeTokenBalance = default(GetUserNativeCurrencyResponseNativeTokenBalance))
        {
            // to ensure "nativeTokenBalance" is required (not null)
            if (nativeTokenBalance == null)
            {
                throw new ArgumentNullException("nativeTokenBalance is a required property for GetUserNativeCurrencyResponse and cannot be null");
            }
            this.NativeTokenBalance = nativeTokenBalance;
        }

        /// <summary>
        /// Gets or Sets NativeTokenBalance
        /// </summary>
        [DataMember(Name = "nativeTokenBalance", IsRequired = true, EmitDefaultValue = true)]
        public GetUserNativeCurrencyResponseNativeTokenBalance NativeTokenBalance { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetUserNativeCurrencyResponse {\n");
            sb.Append("  NativeTokenBalance: ").Append(NativeTokenBalance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
