/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = BeamPlayerClient.Client.OpenAPIDateConverter;

namespace BeamPlayerClient.Model
{
    /// <summary>
    /// WebConnectionRequestInput
    /// </summary>
    [DataContract(Name = "WebConnectionRequestInput")]
    public partial class WebConnectionRequestInput
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="WebConnectionRequestInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected WebConnectionRequestInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="WebConnectionRequestInput" /> class.
        /// </summary>
        /// <param name="message">message (required).</param>
        /// <param name="chainId">chainId (default to 13337M).</param>
        public WebConnectionRequestInput(string message = default(string), decimal chainId = 13337M)
        {
            // to ensure "message" is required (not null)
            if (message == null)
            {
                throw new ArgumentNullException("message is a required property for WebConnectionRequestInput and cannot be null");
            }
            this.Message = message;
            this.ChainId = chainId;
        }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [DataMember(Name = "message", IsRequired = true, EmitDefaultValue = true)]
        public string Message { get; set; }

        /// <summary>
        /// Gets or Sets ChainId
        /// </summary>
        [DataMember(Name = "chainId", EmitDefaultValue = false)]
        public decimal ChainId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class WebConnectionRequestInput {\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  ChainId: ").Append(ChainId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

    }

}
