/*
 * Player API
 *
 * The Player API is a service to integrate your game with Beam
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using BeamPlayerClient.Client;
using BeamPlayerClient.Model;

namespace BeamPlayerClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IActivityApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get asset activity
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="assetId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>CommonActivityResponse</returns>
        CommonActivityResponse GetAssetActivity(string assetAddress, string assetId, CommonActivityRequestInput commonActivityRequestInput);

        /// <summary>
        /// Get asset activity
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="assetId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>ApiResponse of CommonActivityResponse</returns>
        ApiResponse<CommonActivityResponse> GetAssetActivityWithHttpInfo(string assetAddress, string assetId, CommonActivityRequestInput commonActivityRequestInput);
        /// <summary>
        /// Get contract activity
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>CommonActivityResponse</returns>
        CommonActivityResponse GetContractActivity(string assetAddress, CommonActivityRequestInput commonActivityRequestInput);

        /// <summary>
        /// Get contract activity
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>ApiResponse of CommonActivityResponse</returns>
        ApiResponse<CommonActivityResponse> GetContractActivityWithHttpInfo(string assetAddress, CommonActivityRequestInput commonActivityRequestInput);
        /// <summary>
        /// Get user activity
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>CommonActivityResponse</returns>
        CommonActivityResponse GetUserActivity(string entityId, CommonActivityRequestInput commonActivityRequestInput);

        /// <summary>
        /// Get user activity
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>ApiResponse of CommonActivityResponse</returns>
        ApiResponse<CommonActivityResponse> GetUserActivityWithHttpInfo(string entityId, CommonActivityRequestInput commonActivityRequestInput);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IActivityApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get asset activity
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="assetId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CommonActivityResponse</returns>
        Cysharp.Threading.Tasks.UniTask<CommonActivityResponse> GetAssetActivityAsync(string assetAddress, string assetId, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get asset activity
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="assetId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CommonActivityResponse)</returns>
        Cysharp.Threading.Tasks.UniTask<ApiResponse<CommonActivityResponse>> GetAssetActivityWithHttpInfoAsync(string assetAddress, string assetId, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get contract activity
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CommonActivityResponse</returns>
        Cysharp.Threading.Tasks.UniTask<CommonActivityResponse> GetContractActivityAsync(string assetAddress, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get contract activity
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CommonActivityResponse)</returns>
        Cysharp.Threading.Tasks.UniTask<ApiResponse<CommonActivityResponse>> GetContractActivityWithHttpInfoAsync(string assetAddress, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get user activity
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CommonActivityResponse</returns>
        Cysharp.Threading.Tasks.UniTask<CommonActivityResponse> GetUserActivityAsync(string entityId, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get user activity
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CommonActivityResponse)</returns>
        Cysharp.Threading.Tasks.UniTask<ApiResponse<CommonActivityResponse>> GetUserActivityWithHttpInfoAsync(string entityId, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IActivityApi : IActivityApiSync, IActivityApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ActivityApi : IDisposable, IActivityApi
    {
        private BeamPlayerClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ActivityApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ActivityApi(string basePath)
        {
            this.Configuration = BeamPlayerClient.Client.Configuration.MergeConfigurations(
                BeamPlayerClient.Client.GlobalConfiguration.Instance,
                new BeamPlayerClient.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new BeamPlayerClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = BeamPlayerClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ActivityApi(BeamPlayerClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = BeamPlayerClient.Client.Configuration.MergeConfigurations(
                BeamPlayerClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new BeamPlayerClient.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = BeamPlayerClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ActivityApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ActivityApi(BeamPlayerClient.Client.ISynchronousClient client, BeamPlayerClient.Client.IAsynchronousClient asyncClient, BeamPlayerClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = BeamPlayerClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public BeamPlayerClient.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public BeamPlayerClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public BeamPlayerClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public BeamPlayerClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public BeamPlayerClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get asset activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="assetId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>CommonActivityResponse</returns>
        public CommonActivityResponse GetAssetActivity(string assetAddress, string assetId, CommonActivityRequestInput commonActivityRequestInput)
        {
            BeamPlayerClient.Client.ApiResponse<CommonActivityResponse> localVarResponse = GetAssetActivityWithHttpInfo(assetAddress, assetId, commonActivityRequestInput);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get asset activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="assetId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>ApiResponse of CommonActivityResponse</returns>
        public BeamPlayerClient.Client.ApiResponse<CommonActivityResponse> GetAssetActivityWithHttpInfo(string assetAddress, string assetId, CommonActivityRequestInput commonActivityRequestInput)
        {
            // verify the required parameter 'assetAddress' is set
            if (assetAddress == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'assetAddress' when calling ActivityApi->GetAssetActivity");

            // verify the required parameter 'assetId' is set
            if (assetId == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'assetId' when calling ActivityApi->GetAssetActivity");

            // verify the required parameter 'commonActivityRequestInput' is set
            if (commonActivityRequestInput == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'commonActivityRequestInput' when calling ActivityApi->GetAssetActivity");

            BeamPlayerClient.Client.RequestOptions localVarRequestOptions = new BeamPlayerClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = BeamPlayerClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BeamPlayerClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("assetAddress", BeamPlayerClient.Client.ClientUtils.ParameterToString(assetAddress)); // path parameter
            localVarRequestOptions.PathParameters.Add("assetId", BeamPlayerClient.Client.ClientUtils.ParameterToString(assetId)); // path parameter
            localVarRequestOptions.Data = commonActivityRequestInput;

            // authentication (beam-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CommonActivityResponse>("/v1/player/activity/assets/{assetAddress}/asset/{assetId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAssetActivity", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get asset activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="assetId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CommonActivityResponse</returns>
        public async Cysharp.Threading.Tasks.UniTask<CommonActivityResponse> GetAssetActivityAsync(string assetAddress, string assetId, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = GetAssetActivityWithHttpInfoAsync(assetAddress, assetId, commonActivityRequestInput, cancellationToken);
            BeamPlayerClient.Client.ApiResponse<CommonActivityResponse> localVarResponse = await task;
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get asset activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="assetId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CommonActivityResponse)</returns>
        public async Cysharp.Threading.Tasks.UniTask<BeamPlayerClient.Client.ApiResponse<CommonActivityResponse>> GetAssetActivityWithHttpInfoAsync(string assetAddress, string assetId, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'assetAddress' is set
            if (assetAddress == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'assetAddress' when calling ActivityApi->GetAssetActivity");

            // verify the required parameter 'assetId' is set
            if (assetId == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'assetId' when calling ActivityApi->GetAssetActivity");

            // verify the required parameter 'commonActivityRequestInput' is set
            if (commonActivityRequestInput == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'commonActivityRequestInput' when calling ActivityApi->GetAssetActivity");


            BeamPlayerClient.Client.RequestOptions localVarRequestOptions = new BeamPlayerClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = BeamPlayerClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BeamPlayerClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("assetAddress", BeamPlayerClient.Client.ClientUtils.ParameterToString(assetAddress)); // path parameter
            localVarRequestOptions.PathParameters.Add("assetId", BeamPlayerClient.Client.ClientUtils.ParameterToString(assetId)); // path parameter
            localVarRequestOptions.Data = commonActivityRequestInput;

            // authentication (beam-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<CommonActivityResponse>("/v1/player/activity/assets/{assetAddress}/asset/{assetId}", localVarRequestOptions, this.Configuration, cancellationToken);

            var localVarResponse = await task;

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAssetActivity", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get contract activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>CommonActivityResponse</returns>
        public CommonActivityResponse GetContractActivity(string assetAddress, CommonActivityRequestInput commonActivityRequestInput)
        {
            BeamPlayerClient.Client.ApiResponse<CommonActivityResponse> localVarResponse = GetContractActivityWithHttpInfo(assetAddress, commonActivityRequestInput);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get contract activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>ApiResponse of CommonActivityResponse</returns>
        public BeamPlayerClient.Client.ApiResponse<CommonActivityResponse> GetContractActivityWithHttpInfo(string assetAddress, CommonActivityRequestInput commonActivityRequestInput)
        {
            // verify the required parameter 'assetAddress' is set
            if (assetAddress == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'assetAddress' when calling ActivityApi->GetContractActivity");

            // verify the required parameter 'commonActivityRequestInput' is set
            if (commonActivityRequestInput == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'commonActivityRequestInput' when calling ActivityApi->GetContractActivity");

            BeamPlayerClient.Client.RequestOptions localVarRequestOptions = new BeamPlayerClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = BeamPlayerClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BeamPlayerClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("assetAddress", BeamPlayerClient.Client.ClientUtils.ParameterToString(assetAddress)); // path parameter
            localVarRequestOptions.Data = commonActivityRequestInput;

            // authentication (beam-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CommonActivityResponse>("/v1/player/activity/assets/{assetAddress}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetContractActivity", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get contract activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CommonActivityResponse</returns>
        public async Cysharp.Threading.Tasks.UniTask<CommonActivityResponse> GetContractActivityAsync(string assetAddress, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = GetContractActivityWithHttpInfoAsync(assetAddress, commonActivityRequestInput, cancellationToken);
            BeamPlayerClient.Client.ApiResponse<CommonActivityResponse> localVarResponse = await task;
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get contract activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="assetAddress"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CommonActivityResponse)</returns>
        public async Cysharp.Threading.Tasks.UniTask<BeamPlayerClient.Client.ApiResponse<CommonActivityResponse>> GetContractActivityWithHttpInfoAsync(string assetAddress, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'assetAddress' is set
            if (assetAddress == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'assetAddress' when calling ActivityApi->GetContractActivity");

            // verify the required parameter 'commonActivityRequestInput' is set
            if (commonActivityRequestInput == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'commonActivityRequestInput' when calling ActivityApi->GetContractActivity");


            BeamPlayerClient.Client.RequestOptions localVarRequestOptions = new BeamPlayerClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = BeamPlayerClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BeamPlayerClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("assetAddress", BeamPlayerClient.Client.ClientUtils.ParameterToString(assetAddress)); // path parameter
            localVarRequestOptions.Data = commonActivityRequestInput;

            // authentication (beam-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<CommonActivityResponse>("/v1/player/activity/assets/{assetAddress}", localVarRequestOptions, this.Configuration, cancellationToken);

            var localVarResponse = await task;

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetContractActivity", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get user activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>CommonActivityResponse</returns>
        public CommonActivityResponse GetUserActivity(string entityId, CommonActivityRequestInput commonActivityRequestInput)
        {
            BeamPlayerClient.Client.ApiResponse<CommonActivityResponse> localVarResponse = GetUserActivityWithHttpInfo(entityId, commonActivityRequestInput);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get user activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <returns>ApiResponse of CommonActivityResponse</returns>
        public BeamPlayerClient.Client.ApiResponse<CommonActivityResponse> GetUserActivityWithHttpInfo(string entityId, CommonActivityRequestInput commonActivityRequestInput)
        {
            // verify the required parameter 'entityId' is set
            if (entityId == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'entityId' when calling ActivityApi->GetUserActivity");

            // verify the required parameter 'commonActivityRequestInput' is set
            if (commonActivityRequestInput == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'commonActivityRequestInput' when calling ActivityApi->GetUserActivity");

            BeamPlayerClient.Client.RequestOptions localVarRequestOptions = new BeamPlayerClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = BeamPlayerClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BeamPlayerClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("entityId", BeamPlayerClient.Client.ClientUtils.ParameterToString(entityId)); // path parameter
            localVarRequestOptions.Data = commonActivityRequestInput;

            // authentication (beam-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<CommonActivityResponse>("/v1/player/activity/users/{entityId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserActivity", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get user activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of CommonActivityResponse</returns>
        public async Cysharp.Threading.Tasks.UniTask<CommonActivityResponse> GetUserActivityAsync(string entityId, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            var task = GetUserActivityWithHttpInfoAsync(entityId, commonActivityRequestInput, cancellationToken);
            BeamPlayerClient.Client.ApiResponse<CommonActivityResponse> localVarResponse = await task;
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get user activity 
        /// </summary>
        /// <exception cref="BeamPlayerClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="entityId"></param>
        /// <param name="commonActivityRequestInput"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (CommonActivityResponse)</returns>
        public async Cysharp.Threading.Tasks.UniTask<BeamPlayerClient.Client.ApiResponse<CommonActivityResponse>> GetUserActivityWithHttpInfoAsync(string entityId, CommonActivityRequestInput commonActivityRequestInput, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'entityId' is set
            if (entityId == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'entityId' when calling ActivityApi->GetUserActivity");

            // verify the required parameter 'commonActivityRequestInput' is set
            if (commonActivityRequestInput == null)
                throw new BeamPlayerClient.Client.ApiException(400, "Missing required parameter 'commonActivityRequestInput' when calling ActivityApi->GetUserActivity");


            BeamPlayerClient.Client.RequestOptions localVarRequestOptions = new BeamPlayerClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = BeamPlayerClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = BeamPlayerClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.PathParameters.Add("entityId", BeamPlayerClient.Client.ClientUtils.ParameterToString(entityId)); // path parameter
            localVarRequestOptions.Data = commonActivityRequestInput;

            // authentication (beam-api-key) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("x-api-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("x-api-key", this.Configuration.GetApiKeyWithPrefix("x-api-key"));
            }

            // make the HTTP request

            var task = this.AsynchronousClient.PostAsync<CommonActivityResponse>("/v1/player/activity/users/{entityId}", localVarRequestOptions, this.Configuration, cancellationToken);

            var localVarResponse = await task;

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserActivity", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
